# Copyright (C) 2024 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#           docker compose exec db bash
#             ls
#             id
#           docker down

# https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json

services:
  db:
    # 2 statt 12 GB; u.a. genutzt fuer die Entwicklung von Hibernate und Spring Data JPA
    image: gvenzl/oracle-free:23.3-slim
    #image: container-registry.oracle.com/database/express
    ports:
      - published: 1521
        target: 1521
      # https://github.com/gvenzl/oci-oracle-xe/issues/174
      - published: 5500
        target: 5500
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/oracle/oradata
        target: /opt/oracle/oradata
      - type: bind
        source: C:/Zimmermann/volumes/oracle/sql
        target: /sql
        read_only: true
      - type: bind
        source: C:/Zimmermann/volumes/oracle/csv/buch
        target: /csv
    env_file: .env
    # user: oracle:oinstall
    hostname: oracle
    container_name: oracle
    healthcheck:
      # /opt/oracle/healthcheck.sh
      # https://stackoverflow.com/questions/50217637/how-do-i-check-if-oracle-is-up-in-docker
      test: [CMD, bash, -c, healthcheck.sh]
      #test:
      #  [
      #    CMD,
      #    bash,
      #    -c,
      #    "echo 'SELECT 1 FROM dual;' | sqlplus SYS/p@FREEPDB1 AS SYSDBA",
      #  ]
      interval: 120s
      timeout: 5s
      start_period: 30s
    cap_drop: [ALL]
    deploy:
      resources:
        limits:
          cpus: '2.0'
          # https://www.esolution.ca/oracle-database-xe-system-requirements
          # TODO https://github.com/gvenzl/oci-oracle-xe/issues/168
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 512M
